= Agent Fabric Overview

Agent Fabric manages and coordinates the execution of agents across your enterprise, regardless of where they’re deployed. Agent Fabric solves the problem of integrating and automating complex processes that involve multiple agents and tools. 

Complex tasks often require a series of steps, with each step‌ handled by a different agent or tool. Managing this process manually is difficult and error-prone. Broker groups (networks of agents in a domain) act as central hubs for defining, validating, and executing these multistep processes.

Define your ‌agent network in a simple, human-readable YAML file, abstracting away the underlying technical complexities. This approach allows you to focus on the business constraints and context of your process without needing to understand the inner workings of the orchestration engine.

Create robust, automated agent networks with these key benefits.

* Simplified Development
+
Define your agent processes using a simple YAML file, which is easier and faster than writing complex code.
* Safety and Governance
+
A broker group validates your agent network against predefined policies before execution, acting as a safety guardrail.
* Observability
+
After a process runs, view logs and traces to understand the execution path, debug issues, and ensure traceability.
* Flexibility
+
Broker groups coordinate with any type of agent, regardless of where it’s built and deployed, which allows you to build a diverse network of agents.
* Tool and Agent Invocation
+
Manage the invocation of both deterministic (tool-based) and probabilistic (LLM-based) actions.

Broker groups use OpenAI for reasoning and planning capabilities. Broker groups integrate with Anypoint Connector for MCP (Model Context Protocol) and Anypoint Connector for Agent2Agent (A2A). These connectors let you automatically discover and register tools that the LLM can use. You can also specify which agents and MCP servers a broker group can invoke by using an allowlist.

== Architecture

[NEED DIAGRAM]

== Basic Concepts 

=== What’s a broker?

A broker is an intelligent routing service that coordinates task delegation across specialized agents in your enterprise. Brokers are assembled into groups so that Agent Fabric can leverage them to accomplish tasks.

=== What’s a broker group?

A broker group is part of an agent network. It consists of a group of brokers in the same domain and a set of external services (agents and MCP servers) that assist them. You define broker groups in a YAML template which is provided for you.

=== What’s an external agent?

An external agent is outside your broker group. These agents can either be brokers defined in a different broker group, or another agent used in your company.

== Before You Begin

To use Agent Fabric, you must have:

* An Anypoint Platform (Titanium or Anypoint Integration Advanced package). You can use an existing account or create one from Anypoint Platform.
* An OpenAI instance and login credentials. 
* A managed Flex Gateway.
* CloudHub 2.0 with Managed Flex Gateway and private space entitlements.

Also, have this software installed.

* Visual Studio Code (VS Code) with latest updates and code command configured in $PATH. For more information, see https://code.visualstudio.com/docs/setup/mac#_launch-vs-code-from-the-command-line[Launch VS Code from the command line].
* PowerShell (Windows operating systems only). For more information, see https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.5&viewFallbackFrom=powershell-7.3[Installing PowerShell on Windows].
PowerShell (Windows operating systems only). For more information, see Installing PowerShell on Windows.

== Authentication Types

These authentication types are supported.

* Basic
* Client Credentials
* Anypoint Client Credentials


== See Also

* xref:agent-fabric-get-started.adoc[]
* xref:anypoint-code-builder::index.adoc[]
* xref:exchange::index.adoc[]