= Agent Conductor Overview

Agent Conductor helps you with your multi-agent strategy as you move into a multi-agent world. Its main function is to act as an intelligent orchestrator, or router, that ensures the correct agents are activated at the appropriate time to handle specific sub-tasks. This allows a network of different agents to work together to accomplish your business goals. 

Agent Conductor:

* Can coordinate with any type of agent, not just proprietary ones, which allows you to build a diverse network of agents.

* Leverages Einstein LLM by default for its reasoning and planning capabilities.

* Integrates with MCP (MuleSoft Common Protocol) and A2A (Agent-to-Agent) connectors to automatically discover and register tools that the LLM can use. You can also specify which agents and MCP servers the Conductor can invoke by using an "allow-list" in the declarative specification file.

* Uses the A2A protocol's state management layer to track the progress of a workflow and maintain context in ongoing orchestrations.

* Includes a max loop parameter to prevent runaway processes.

* Provides basic observability and traceability. You will be able to view logs and traces after a workflow has been executed, which will help you debug and understand the decision paths taken.

== Before You Begin

You must:

* Install Anypoint Code Builder.
* Have an Anypoint Platform account.



== See Also

* xref:code-builder::index.adoc[]
* xref:gateway::index.adoc[]
* xref:exchange::index.adoc[]